### ISSUE TITLE
Site broken with multiple problems occurring

### ISSUE THREAD

**Issue by clydeclements** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#143]
Vanessa notified me of problems occurring with the Ocean Navigator site today. I can confirm there are multiple problems:

- With the default view of GIOPS data, the Time field is showing "NaN" instead of an actual date.
- I am unable to select any date: no calendar popup is presented; the left and right arrow buttons to select the previous or next date are not working.
- Selecting the RIOPS data set, I get a "Please Wait" window. After several minutes, no RIOPS data is displayed and the "Please Wait" window is still shown.

**Comment by clydeclements** [comment]
Looking at the log file for the Python application, I see messages like this:
```
syntax error, unexpected WORD_STRING, expecting WORD_WORD
context: Error { code = 404; message = "/data/GIOPS/daily/aggregated.ncml (Too many open files)"^;};
Traceback (most recent call last):
  File "/opt/tools/anaconda/2/4.2.0/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/tools/anaconda/2/4.2.0/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/tools/anaconda/2/4.2.0/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tools/anaconda/2/4.2.0/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/tools/anaconda/2/4.2.0/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/tools/anaconda/2/4.2.0/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tools/anaconda/2/4.2.0/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/tools/anaconda/2/4.2.0/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/buildadm/src/navigator/oceannavigator/views.py", line 347, in time_query
    with open_dataset(get_dataset_url(dataset)) as ds:
  File "/home/buildadm/src/navigator/data/__init__.py", line 15, in open_dataset
    with Dataset(url, 'r') as ds:
  File "netCDF4/_netCDF4.pyx", line 1811, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:12626)
IOError: NetCDF: file not found
```
There are a bunch of error messages similar to this in the log file. The above message contains "syntax error", "too many open files", and "file not found". It's not immediately obvious what the source of problem is.

Some other things I check:
- disk usage was fine; at least no disks full
- system usage (from top and ps) appeared fine; nothing unexpected
- the number of open files (obtained with `sudo lsof | wc -l`) was about 360000; high but I believe we have seen that high before

In an effort to return Ocean Navigator to a functional state as soon as possible, I restarted the `uwsgi-emperor` service (which runs the Python app). After checking the website, problems still persisted and it appeared to have no benefit.

I then checked the THREDSS site. That was not working; in particular, I could not navigate through the folder structure. That lead me to one of the Tomcat log files (`localhost.2017-12-01`) which had the following exception-thrown message:
```
Dec 01, 2017 10:45:14 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [root] in context with path [/thredds] threw exception
dap4.core.util.DapException: dap4.core.util.DapException: Resource root not found
        at dap4.servlet.DapRequest.<init>(DapRequest.java:78)
        at dap4.servlet.DapController.getRequestState(DapController.java:415)
        at dap4.servlet.DapController.handleRequest(DapController.java:185)
```
There were actually many occurrences of this type of message in the log file. Another Tomcat log file (`catalina.out`) had the following messages:
```
Dec 01, 2017 2:31:23 PM org.apache.tomcat.util.net.JIoEndpoint$Acceptor run
SEVERE: Socket accept failed
java.net.SocketException: Too many open files (Accept failed)
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at org.apache.tomcat.util.net.DefaultServerSocketFactory.acceptSocket(DefaultServerSocketFactory.java:60)
        at org.apache.tomcat.util.net.JIoEndpoint$Acceptor.run(JIoEndpoint.java:219)
        at java.lang.Thread.run(Thread.java:745)

Dec 01, 2017 2:31:35 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 2.
Dec 01, 2017 2:31:35 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Dec 01, 2017 2:31:36 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock System prefs. Unix error code 32510.
```
Again, there were many occurrences of these type of messages in that file. So clearly Tomcat, and therefore THREDDS, was in a bad state. To resolve this, I restarted the `tomcat7` service. With that done, the Ocean Navigator site appears to be functional again. I can view GIOPS data and select different dates, and I can select other data sets such as RIOPS and they load fine.

Note: Restarting `tomcat7` and `uwsgi-emperor` was a quick fix, but I do not know what lead to the corrupted state of these services. A quick perusal of the log files doesn't reveal the trigger event.

**Comment by htmlboss** [comment]
I did some googling (https://stackoverflow.com/questions/19636676/error-in-tomcat-too-many-open-files), and ran the following commands to see what the limit for open files is for tomcat:

`sudo ps -aux | grep tomcat`
`tomcat7  22210  3.1  6.7 113111304 17936108 ?  Sl   Dec01 498:05 /usr/lib/jvm/default-java/bin/java....`

`sudo cat /proc/22210/limits`
![image](https://user-images.githubusercontent.com/5572045/33884186-499aeac2-df19-11e7-9223-4b6ea2e3c233.png)

So it seems like we're limited to 4096 open files.

Thing is, it's very possible we're leaking file handles somwhere...

**Comment by htmlboss** [comment]
Seems like we are leaking files:

`sudo ls -l /proc/22210/fd`

This produces a ton of output with symlinks (I think) to .nc files.

**Comment by htmlboss** [comment]
According to the THREDDS docs (https://www.unidata.ucar.edu/software/thredds/v5.0/tds/faq.html):
Q: Can aggregations of many files cause ``too many files open''

Union type agregations will open all the files in the aggregation at once. The other types (joinNew, joinExisting) only open one file at a time, and then close it, so these can’t cause ``too many file'' problems.

If you have ``too many open files'' errors and you are not using large Union aggregations, then either theres a file leak (which we would like to know about), or you have your file cache limit set too high relative to your OS file handle limit.

To debug file leaks:

Check number of open files with ``ulimit -a''.

Restart Tomcat to close open files.

Monitor open files with ``/usr/proc/bin/pfiles [Tomcat Process ID]'' (this won't work on Linux systems so we use `ls -l /proc/22210/fd`)

Recreate the problem with minimal number of steps so we can reproduce, then send pfiles output to support.

**Comment by htmlboss** [comment]
debug script is written (after several epic fails) and now we wait. It's logged at `/var/log/ocean-navigator-open-files.log`

**Comment by Jeffreydaw** [comment]
When the site crashed since the logging script was set up. The log file `/var/log/ocean-navigator-open-files.log` did not show anything that was amiss
