### ISSUE TITLE
Threads Crash

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#170]
On Friday (Jan 19 2017)  the Thredds server crashed. many of the log files did not record anything the one that did report the last report before the crash was at  _Jan 19, 2018 4:47:52 PM_   the server was brought back up at around 8:35 PM UTC

WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Jan 19, 2018 4:46:23 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock System prefs. Unix error code 32645.
Jan 19, 2018 4:46:23 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Jan 19, 2018 4:46:51 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 2.
Jan 19, 2018 4:46:51 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Jan 19, 2018 4:46:53 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock System prefs. Unix error code 32646.
Jan 19, 2018 4:46:53 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Jan 19, 2018 4:47:21 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 2.
Jan 19, 2018 4:47:21 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Jan 19, 2018 4:47:23 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock System prefs. Unix error code 32646.
Jan 19, 2018 4:47:23 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Jan 19, 2018 4:47:52 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 2.
Jan 19, 2018 4:47:52 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Jan 19, 2018 8:35:33 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common/classes], exists: [false], isDirectory: [false], canRead: [false]
Jan 19, 2018 8:35:33 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common], exists: [false], isDirectory: [false], canRead: [false]
Jan 19, 2018 8:35:33 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server/classes], exists: [false], isDirectory: [false], canRead: [false]
Jan 19, 2018 8:35:33 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server], exists: [false], isDirectory: [false], canRead: [false]
Jan 19, 2018 8:35:33 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
Jan 19, 2018 8:35:33 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared], exists: [false], isDirectory: [false], canRead: [false]
Jan 19, 2018 8:35:34 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Jan 19, 2018 8:35:34 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8443"]
Jan 19, 2018 8:35:34 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 943 ms
Jan 19, 2018 8:35:34 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Jan 19, 2018 8:35:34 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.52 (Ubuntu)
Jan 19, 2018 8:35:34 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/host-manager.xml
Jan 19, 2018 8:35:35 PM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/manager.xml
Jan 19, 2018 8:35:35 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/thredds.war
2018-01-19 20:35:44,247 ERROR FileManager (/data/thredds/logs/serverStartup.log) java.io.FileNotFoundException: /data/thredds/logs/serverStartup.log (Permission denied)
2018-01-19 20:35:44,249 ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.FileAppender for element File. java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:135)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:766)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:706)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:698)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:358)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:161)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:359)

___________________________________________________________________________________
Possible fixes:
https://confluence.atlassian.com/confkb/could-not-lock-user-prefs-unix-error-code-2-670958391.html
https://issues.sonatype.org/browse/NEXUS-3671
https://stackoverflow.com/questions/23960451/java-system-preferences-under-different-users-in-linux

**Comment by Jeffreydaw** [comment]
I changed the file permissions on the log files for thredds since for some reason threads did not have write access to it's own log files. now files that have not been written to for a long time are logging again. 

I am seeing a new error.  in catalina.out
`WARNING: Problem with directory [/usr/share/tomcat7/common/classes], exists: [false], isDirectory: [false], canRead: [false]

Jan 22, 2018 3:58:51 PM org.apache.catalina.startup.ClassLoaderFactory validateFile`

which seems to be related to 
https://stackoverflow.com/questions/27337674/folder-issues-with-tomcat-7-on-ubuntu
https://bugs.launchpad.net/ubuntu/+source/tomcat7/+bug/1232258

**Comment by Jeffreydaw** [comment]
ok I've implemented a few changes. 
including 
#sudo mkdir /usr/share/tomcat7/.java
#sudo mkdir /usr/share/tomcat7/.java/.userPrefs
#sudo chown -R tomcat7:tomcat7 /usr/share/tomcat7/.java

hopeful this will have the issue fixed. it seems to take a while for it to appear in the log files, so we will just have to wait and see. 

possibility related to issue:  #143 though I did check the file logging the number of open files and it did not seem high.
