### ISSUE TITLE
CSV for water velocity with direction have no data. 

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#337]
some area plots won't download the csv for water veloicity ~for the bottom depth~

[link](http://navigator.oceansdata.ca/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B61.04639389126788%2C-425.40145874023415%5D%2C%5B62.19505370938609%2C-417.00790405273415%5D%2C%5B51.956207606138406%2C-403.8243103027341%5D%2C%5B46.39062066937461%2C-399.47372436523415%5D%2C%5B41.22629657141934%2C-410.81161499023415%5D%2C%5B41.916697178017586%2C-417.66708374023415%5D%2C%5B48.90635310933598%2C-417.2276306152341%5D%2C%5B51.274038424378375%2C-416.61239624023415%5D%2C%5B53.31619823816382%2C-418.10653686523415%5D%2C%5B53.39488417825268%2C-423.2481384277341%5D%2C%5B58.01836206968312%2C-425.0498962402341%5D%2C%5B61.04639389126788%2C-425.40145874023415%5D%5D%5D%7D%5D%2C%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%22-393.1284%22%2C%2251.3564%22%5D%2C%22dataset%22%3A%22giops_month%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22starttime%22%3A-2%2C%22time%22%3A-1%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A%22bottom%22%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22convertToUserGrid%22%3Afalse%2C%22currentTab%22%3A1%2C%22dataset_0%22%3A%7B%22dataset%22%3A%22giops_month%22%2C%22dataset_attribution%22%3A%22GIOPS%20Monthly%20Averages%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22month%22%2C%22depth%22%3A%22bottom%22%2C%22time%22%3A12%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22variable_scale%22%3A%5B0%2C3%5D%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A13%2C%22output_format%22%3A%22NETCDF4%22%2C%22output_starttime%22%3A13%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%220%2C3%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22setDefaultScale%22%3Atrue%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22syncLocalToGlobalState%22%3Afalse%2C%22zip%22%3Afalse%7D%2C%22time%22%3A13%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A5%7D)

[bad gatway 502 error](http://navigator.oceansdata.ca/plot/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B61.113351826947024%2C-425.1672443283691%5D%2C%5B62.23910926507082%2C-416.8615802658691%5D%2C%5B52.230266779776%2C-403.8537677658692%5D%2C%5B46.304189094492926%2C-399.1955646408691%5D%2C%5B41.30023994079224%2C-411.049234058957%5D%2C%5B42.152959049669846%2C-417.465249683957%5D%2C%5B48.91324057284814%2C-417.3773590589569%5D%2C%5B51.170509722279235%2C-416.454507496457%5D%2C%5B53.558045780838114%2C-418.344155933957%5D%2C%5B53.32245807980647%2C-423.002359058957%5D%2C%5B58.325169608455724%2C-425.1556793714569%5D%2C%5B61.113351826947024%2C-425.1672443283691%5D%5D%5D%7D%5D%2C%22bathymetry%22%3Atrue%2C%22colormap%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22dataset%22%3A%22giops_month%22%2C%22depth%22%3A%224%22%2C%22interp%22%3A%22gaussian%22%2C%22neighbours%22%3A10%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22quantum%22%3A%22month%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D%2C%22radius%22%3A25%2C%22scale%22%3A%220%2C3%2Cauto%22%2C%22showarea%22%3Atrue%2C%22time%22%3A25%2C%22type%22%3A%22map%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D&save&format=csv&size=10x7&dpi=144)

when acessing the same data on trinity the problem is not seen

GIOPS Monthly with arrows

**Comment by Jeffreydaw** [comment]
For GLORYS_v4 it seems that that the CSV works for the bottom but nothing else can actually causes a 502 error

    [pid: 12345|app: 0|req: 1017/11703] 205.194.26.21 () {42 vars in 2953 bytes} [Thu Sep 20 13:12:56 2018] GET /plot/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B48.790679959856675%2C-55.30776977539061%5D%2C%5B45.50452752676773%2C-50.298004150390604%5D%2C%5B47.04219931931533%2C-46.96081271515922%5D%2C%5B53.48980668549456%2C-53.201047090159214%5D%2C%5B48.790679959856675%2C-55.30776977539061%5D%5D%5D%7D%5D%2C%22bathymetry%22%3Atrue%2C%22colormap%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22dataset%22%3A%22glorys4%22%2C%22depth%22%3A0%2C%22interp%22%3A%22gaussian%22%2C%22neighbours%22%3A10%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22quantum%22%3A%22month%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D%2C%22radius%22%3A25%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22showarea%22%3Atrue%2C%22time%22%3A275%2C%22type%22%3A%22map%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D&save&format=csv&size=10x7&dpi=144 => generated 504259 bytes in 14758 msecs (HTTP/1.1 200) 4 headers in 198 bytes (4 switches on core 0)
    /opt/tools/miniconda3/lib/python3.6/site-packages/matplotlib/contour.py:1484: UserWarning: Log scale: values of z <= 0 have been masked
      warnings.warn('Log scale: values of z <= 0 have been masked')
    /opt/tools/miniconda3/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:1708: 
    MatplotlibDeprecationWarning: The axesPatch function was deprecated in version 2.1. Use Axes.patch instead.
      limb = ax.axesPatch
    /opt/tools/miniconda3/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:1711: 
    MatplotlibDeprecationWarning: The axesPatch function was deprecated in version 2.1. Use Axes.patch instead.
      if limb is not ax.axesPatch:
    GET /plot/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B48.790679959856675%2C-55.30776977539061%5D%2C%5B45.50452752676773%2C-50.298004150390604%5D%2C%5B47.04219931931533%2C-46.96081271515922%5D%2C%5B53.48980668549456%2C-53.201047090159214%5D%2C%5B48.790679959856675%2C-55.30776977539061%5D%5D%5D%7D%5D%2C%22bathymetry%22%3Atrue%2C%22colormap%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22dataset%22%3A%22glorys4%22%2C%22depth%22%3A%2213%22%2C%22interp%22%3A%22gaussian%22%2C%22neighbours%22%3A10%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22quantum%22%3A%22month%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D%2C%22radius%22%3A25%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22showarea%22%3Atrue%2C%22time%22%3A275%2C%22type%22%3A%22map%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D&format=json => generated 378292 bytes in 10750 msecs (HTTP/1.1 200) 5 headers in 150 bytes (3 switches on core 0)
    Traceback (most recent call last):
      File "/opt/tools/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
      File "/opt/tools/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
      File "/opt/tools/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
      File "/opt/tools/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
      File "/opt/tools/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
      File "/opt/tools/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
      File "/opt/tools/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
      File "/opt/tools/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
      File "/opt/tools/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
      File "/opt/tools/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/buildadm/src/navigator/routes/api_v0_0.py", line 200, in plot_v0
    return routes.routes_impl.plot_impl(request.args)
      File "/home/buildadm/src/navigator/routes/routes_impl.py", line 789, in plot_impl
    img, mime, filename = plotter.run(size=size, dpi=args.get('dpi'))
      File "/home/buildadm/src/navigator/plotting/plotter.py", line 61, in run
    self.prepare_plot(**kwargs)
      File "/home/buildadm/src/navigator/plotting/plotter.py", line 54, in prepare_plot
    self.load_data()
      File "/home/buildadm/src/navigator/plotting/map.py", line 400, in load_data
    d[np.where(quiver_bathymetry < depth_value)] = np.ma.masked
    ValueError: operands could not be broadcast together with shapes (50,50) (500,340) 
    [pid: 12345|app: 0|req: 1019/11705] 205.194.26.21 () {42 vars in 2967 bytes} [Thu Sep 20 13:15:41 2018] GET /plot/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B48.790679959856675%2C-55.30776977539061%5D%2C%5B45.50452752676773%2C-50.298004150390604%5D%2C%5B47.04219931931533%2C-46.96081271515922%5D%2C%5B53.48980668549456%2C-53.201047090159214%5D%2C%5B48.790679959856675%2C-55.30776977539061%5D%5D%5D%7D%5D%2C%22bathymetry%22%3Atrue%2C%22colormap%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22dataset%22%3A%22glorys4%22%2C%22depth%22%3A%2213%22%2C%22interp%22%3A%22gaussian%22%2C%22neighbours%22%3A10%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22quantum%22%3A%22month%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D%2C%22radius%22%3A25%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22showarea%22%3Atrue%2C%22time%22%3A275%2C%22type%22%3A%22map%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D&save&format=csv&size=10x7&dpi=144 => generated 0 bytes in 9309 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)



[GLORYS without vectors 1m (CSV works)](http://navigator.oceansdata.ca/public/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B48.790679959856675%2C-55.30776977539061%5D%2C%5B45.50452752676773%2C-50.298004150390604%5D%2C%5B47.04219931931533%2C-46.96081271515922%5D%2C%5B53.48980668549456%2C-53.201047090159214%5D%2C%5B48.790679959856675%2C-55.30776977539061%5D%5D%5D%7D%5D%2C%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%22-50.3542%22%2C%2252.8577%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22starttime%22%3A-2%2C%22time%22%3A-1%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22convertToUserGrid%22%3Afalse%2C%22currentTab%22%3A1%2C%22dataset_0%22%3A%7B%22dataset%22%3A%22glorys4%22%2C%22dataset_attribution%22%3A%22GLORYS2V4%20from%20Mercator%20Ocean%22%2C%22dataset_quantum%22%3A%22month%22%2C%22depth%22%3A0%2C%22time%22%3A926%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22variable_scale%22%3A%220%2C3%22%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A926%2C%22output_format%22%3A%22NETCDF4%22%2C%22output_starttime%22%3A926%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22none%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22setDefaultScale%22%3Atrue%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22syncLocalToGlobalState%22%3Afalse%2C%22zip%22%3Afalse%7D%2C%22time%22%3A926%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A4%7D)

[GLORYS with vectors 1 m CSV downloads (works) ](http://navigator.oceansdata.ca/public/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B48.790679959856675%2C-55.30776977539061%5D%2C%5B45.50452752676773%2C-50.298004150390604%5D%2C%5B47.04219931931533%2C-46.96081271515922%5D%2C%5B53.48980668549456%2C-53.201047090159214%5D%2C%5B48.790679959856675%2C-55.30776977539061%5D%5D%5D%7D%5D%2C%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%22-50.3542%22%2C%2252.8577%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22starttime%22%3A-2%2C%22time%22%3A-1%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22convertToUserGrid%22%3Afalse%2C%22currentTab%22%3A1%2C%22dataset_0%22%3A%7B%22dataset%22%3A%22glorys4%22%2C%22dataset_attribution%22%3A%22GLORYS2V4%20from%20Mercator%20Ocean%22%2C%22dataset_quantum%22%3A%22month%22%2C%22depth%22%3A0%2C%22time%22%3A926%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22variable_scale%22%3A%220%2C3%22%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A926%2C%22output_format%22%3A%22NETCDF4%22%2C%22output_starttime%22%3A926%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22setDefaultScale%22%3Atrue%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22syncLocalToGlobalState%22%3Afalse%2C%22zip%22%3Afalse%7D%2C%22time%22%3A926%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A4%7D)


[GLORYS with vectors 27 m (breaks causeing bad gateway)](http://navigator.oceansdata.ca/public/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B48.790679959856675%2C-55.30776977539061%5D%2C%5B45.50452752676773%2C-50.298004150390604%5D%2C%5B47.04219931931533%2C-46.96081271515922%5D%2C%5B53.48980668549456%2C-53.201047090159214%5D%2C%5B48.790679959856675%2C-55.30776977539061%5D%5D%5D%7D%5D%2C%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%22-50.3542%22%2C%2252.8577%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22starttime%22%3A-2%2C%22time%22%3A-1%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22convertToUserGrid%22%3Afalse%2C%22currentTab%22%3A1%2C%22dataset_0%22%3A%7B%22dataset%22%3A%22glorys4%22%2C%22dataset_attribution%22%3A%22GLORYS2V4%20from%20Mercator%20Ocean%22%2C%22dataset_quantum%22%3A%22month%22%2C%22depth%22%3A%2213%22%2C%22time%22%3A275%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22variable_scale%22%3A%220%2C3%22%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A926%2C%22output_format%22%3A%22NETCDF4%22%2C%22output_starttime%22%3A926%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22setDefaultScale%22%3Atrue%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22syncLocalToGlobalState%22%3Afalse%2C%22zip%22%3Afalse%7D%2C%22time%22%3A926%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A4%7D)

**Comment by Jeffreydaw** [comment]
This issue has been resolved in [v3.0.4](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/releases/tag/v3.0.4)
