### ISSUE TITLE
Trying to integrate CMEMS monthly data

### ISSUE THREAD

**Issue by dwayne-hart** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#560]
**Describe the bug**
Using version 0.14 of the nc-timestamp-mapper indexing tool. The SQLite database does get created. However, when I update the datasetconfig.json file with the following data descriptors...

    "CMEMS_MONTHLY": {
        "name": "CMEMS Monthly 1993 to 2018",
        "enabled": true,
        "url": "/home/buildadm/ocean-nav/db/CMEMS-MONTHLY.sqlite3",
        "help": "Ask Corinne",
        "attribution": "Ask Corinne",
        "quantum": "hour",
        "type": "historical",
        "time_dim_name": "seconds since 1950-01-01 00:00:00",
        "climatology": "",
        "lat_var_key": "latitude",
        "lon_var_key": "longitude",
        "variables": {
            "uo": { "name": "Water X Velocity", "unit": "m/s", "scale": [-3, 3], "zero_centered": "true" },
            "vo": { "name": "Water Y Velocity", "unit": "m/s", "scale": [-3, 3], "zero_centered": "true" },
            "uo,vo": { "name": "Water Velocity", "unit": "m/s", "scale": [0, 3] },
            "thetao": { "name": "Temperature", "unit": "Celisus", "scale": [-5, 30], "equation": "thetao - 273.15", "dims": ["time", "latitude", "longitude"] },
            "so": { "name": "Salinity", "unit": "PSU", "scale": [30, 40] },
            "zos": { "name": "Sea Surface Height", "unit": "m", "scale": [-3, 3], "zero_centered": "true" }
        }
    }

When I select the menu entry for this data set the following message is printed in the terminal session running the gunicorn process;

[2019-11-20 19:46:04 -0400] [2615] [ERROR] Error handling request /api/v1.0/timestamps/?dataset=CMEMS_MONTHLY&variable=so
Traceback (most recent call last):
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/buildadm/ocean-nav/Ocean-Data-Map-Project/routes/api_v1_0.py", line 384, in timestamps
    converted_vals = time_index_to_datetime(vals, config.time_dim_units)
  File "/home/buildadm/ocean-nav/Ocean-Data-Map-Project/data/utils.py", line 95, in time_index_to_datetime
    t = cftime.utime(time_units)
  File "cftime/_cftime.pyx", line 1015, in cftime._cftime.utime.__init__
  File "cftime/_cftime.pyx", line 88, in cftime._cftime._parse_date_and_units
  File "cftime/_cftime.pyx", line 53, in cftime._cftime._datesplit
AttributeError: 'NoneType' object has no attribute 'split'

**Expected behavior**
The CMEMS data set has the following variables 
**Screenshots**

**Additional context**
A sample data file containing all its variables can be viewed at http://dory-dev.cs.dal.ca/thredds/dodsC/CMEMS2009LL/aggregated.ncml.html

**Comment by dwayne-hart** [comment]
I have made a change to the datasetconfig.json file with the following data descriptors;

    "CMEMS_MONTHLY": {
        "name": "CMEMS Monthly 1993 to 2018",
        "enabled": true,
        "climatology": "http://10.0.3.56:8080/thredds/dodsC/climatology/Levitus98_PHC21/aggregated.ncml",
        "url": "/home/buildadm/ocean-nav/db/CMEMS-MONTHLY.sqlite3",
        "help": "",
        "attribution": "",
        "quantum": "hour",
        "type": "historical",
        "time_dim_name": "hours since 1950-01-01 00:00:00",
        "lat_var_key": "latitude",
        "lon_var_key": "longitude",
        "variables": {
            "uo": { "name": "Water X Velocity", "unit": "m/s", "scale": [-3, 3], "zero_centered": "true" },
            "vo": { "name": "Water Y Velocity", "unit": "m/s", "scale": [-3, 3], "zero_centered": "true" },
            "uo,vo": { "name": "Water Velocity", "unit": "m/s", "scale": [0, 3] },
            "thetao": { "name": "Temperature", "unit": "Celisus", "scale": [-5, 30], "equation": "thetao - 273.15", "dims": ["time", "latitude", "longitude"] },
            "so": { "name": "Salinity", "unit": "PSU", "scale": [30, 40] },
            "zos": { "name": "Sea Surface Height", "unit": "m", "scale": [-3, 3], "zero_centered": "true" }
     
Essentially the change was "time_dim_name": "seconds since 1950-01-01 00:00:00", to "time_dim_name": "hours since 1950-01-01 00:00:00",

**Comment by dwayne-hart** [comment]
I went from tag version 4.1.4 straight to what is currently sitting on master (recent merge of Nabil's code). Still an issue exists...

(navigator) buildadm@u1604-on-production-b:~/ocean-nav/Ocean-Data-Map-Project$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   data/calculated_parser/parser.out
        modified:   data/calculated_parser/parsetab.py
        modified:   oceannavigator/datasetconfig.json
        modified:   oceannavigator/oceannavigator.cfg
        modified:   runserver.sh

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        oceannavigator/frontend/yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")

the same issue is present...

[2019-11-20 20:19:48 -0400] [3040] [INFO] Booting worker with pid: 3040
Generating LALR tables
[2019-11-20 20:20:15 -0400] [3032] [ERROR] Error handling request /api/v1.0/timestamps/?dataset=CMEMS_MONTHLY&variable=so
Traceback (most recent call last):
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/buildadm/ocean-nav/Ocean-Data-Map-Project/routes/api_v1_0.py", line 384, in timestamps
    converted_vals = time_index_to_datetime(vals, config.time_dim_units)
  File "/home/buildadm/ocean-nav/Ocean-Data-Map-Project/data/utils.py", line 95, in time_index_to_datetime
    t = cftime.utime(time_units)
  File "cftime/_cftime.pyx", line 1015, in cftime._cftime.utime.__init__
  File "cftime/_cftime.pyx", line 88, in cftime._cftime._parse_date_and_units
  File "cftime/_cftime.pyx", line 53, in cftime._cftime._datesplit
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by htmlboss** [comment]
Issue was with `time_dim_units` being incorrectly referred to as `time_dim_name`.
