### ISSUE TITLE
Incorporating SeaDOO data sets

### ISSUE THREAD

**Issue by dwayne-hart** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#578]
In trying to add SeaDOO user-grid datasets to the Navigator, we get the following exception from the Mercator class:

```sh
Traceback (most recent call last):
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/buildadm/ocean-nav/Ocean-Data-Map-Project/routes/api_v1_0.py", line 474, in tile_v1_0
    return routes.routes_impl.tile_impl(projection, interp, radius, neighbours, dataset, variable, timestamp, depth, scale, masked, display, zoom, x, y)
  File "/home/buildadm/ocean-nav/Ocean-Data-Map-Project/routes/routes_impl.py", line 618, in tile_impl
    'display': display[1]
  File "/home/buildadm/ocean-nav/Ocean-Data-Map-Project/plotting/tile.py", line 215, in plot
    with open_dataset(config, variable=variable, timestamp=time) as dataset:
  File "/home/buildadm/ocean-nav/Ocean-Data-Map-Project/data/mercator.py", line 36, in __enter__
    self.__latsort = np.argsort(self.latvar[:])
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1034, in argsort
    return _wrapfunc(a, 'argsort', axis=axis, kind=kind, order=order)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/xarray/core/variable.py", line 1660, in func
    return self.__array_wrap__(f(self.data, *args, **kwargs))
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/xarray/core/ops.py", line 207, in func
    return _call_possibly_missing_method(self, name, args, kwargs)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/xarray/core/ops.py", line 189, in _call_possibly_missing_method
    duck_array_ops.fail_on_dask_array_input(arg, func_name=name)
  File "/home/sdfo000/ocean-nav/miniconda/3/envs/navigator/lib/python3.6/site-packages/xarray/core/duck_array_ops.py", line 59, in fail_on_dask_array_input
    raise NotImplementedError(msg % func_name)
NotImplementedError: 'argsort' is not yet a valid method on dask arrays
```

**Comment by htmlboss** [comment]
Turns out we aren't using the `__latsort` and `__lonsort` variables which is rather strange. Simply removing them would resolve the problem, but that begs the question are we showing the data correctly with Mercator?

**Comment by nsoontie** [comment]
A couple of comments.

1. Is it necessary to sort the latitude and longitudes?
2. If the self.latvar, self.lonvar weren't dask arrays could they be sorted? Or would that have a negative impact on performance?

**Comment by htmlboss** [comment]
Blocked until we figure out what to do with the new ui on master. Will update accordingly.

**Comment by htmlboss** [comment]
`master` was reverted to an October 2019 commit and so a fix was implemented for this.
