### ISSUE TITLE
API Stability: Stats Endpoint

### ISSUE THREAD

**Issue by jamesprayner** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#674]
**Describe the bug**
Requesting stats for any area returns:
`RuntimeError: Opening a dataset via sqlite requires the 'variable' keyword argument.`
This makes me think it is a issue with the indexing tool.

Full stack:
```
Traceback (most recent call last):
  File "/home/buildadm/miniconda/3/ubuntu/16.04/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/buildadm/miniconda/3/ubuntu/16.04/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/buildadm/miniconda/3/ubuntu/16.04/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/buildadm/miniconda/3/ubuntu/16.04/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/buildadm/miniconda/3/ubuntu/16.04/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/buildadm/miniconda/3/ubuntu/16.04/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/buildadm/miniconda/3/ubuntu/16.04/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/buildadm/miniconda/3/ubuntu/16.04/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/buildadm/miniconda/3/ubuntu/16.04/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/buildadm/miniconda/3/ubuntu/16.04/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/buildadm/Ocean-Data-Map-Project/routes/api_v1_0.py", line 403, in stats_v1_0
    with open_dataset(config) as dataset:
  File "/home/buildadm/Ocean-Data-Map-Project/utils/decorators.py", line 71, in lru_decorator
    return cached_function(*_args, **_kwargs)
  File "/home/buildadm/Ocean-Data-Map-Project/utils/decorators.py", line 61, in func_with_serialized_params
    return func(*_args, **_kwargs)
  File "/home/buildadm/Ocean-Data-Map-Project/data/__init__.py", line 71, in open_dataset
    __check_required_kwargs(**kwargs)
  File "/home/buildadm/Ocean-Data-Map-Project/data/__init__.py", line 106, in __check_required_kwargs
    "Opening a dataset via sqlite requires the 'variable' keyword argument.")
RuntimeError: Opening a dataset via sqlite requires the 'variable' keyword argument.
```

**To Reproduce**
Request the following query, or any valid of the form `/api/v1.0/stats/...`
```
/api/v1.0/stats/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B49.837982453084834%2C-46.26480102539064%5D%2C%5B49.78126405817835%2C-39.67300415039064%5D%2C%5B46.55886030311717%2C-40.11245727539064%5D%2C%5B46.55886030311717%2C-46.96792602539063%5D%2C%5B49.837982453084834%2C-46.26480102539064%5D%5D%5D%7D%5D%2C%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22time%22%3A2214388800%2C%22variable%22%3A%22votemper%22%7D
```

**Expected behavior**
Statistics should be calculated and sent to the user.

**Comment by JustinElms** [comment]
stats endpoint was removed
