### ISSUE TITLE
Area Setting Arrows not rendering

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#713]
I selected the area plot to display surface velocity and tried to add the velocity arrows. The arrows are not rendering.

![image](https://user-images.githubusercontent.com/30048431/78786425-4eec3100-7983-11ea-9a39-f01c12d6b649.png)

Url:
http://navigator.oceansdata.ca/public/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B51.835777520452496%2C-54.5443707704544%5D%2C%5B45.460130637921%2C-41.82952523231505%5D%2C%5B41.200699508460985%2C-46.80999577045439%5D%2C%5B41.98943703321646%2C-55.188903808593764%5D%2C%5B51.835777520452496%2C-54.5443707704544%5D%5D%5D%7D%5D%2C%22center%22%3A%5B%22-49.7070%22%2C%2253.0000%22%5D%2C%22dataset%22%3A%22cmems_seasonal_climatolog%22%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22convertToUserGrid%22%3Afalse%2C%22currentTab%22%3A1%2C%22dataset_0%22%3A%7B%22dataset%22%3A%22cmems_seasonal_climatolog%22%2C%22dataset_attribution%22%3A%22E.U.%20Copernicus%20Marine%20Service%20Information%20(CMEMS)%22%2C%22dataset_quantum%22%3A%22month%22%2C%22depth%22%3A0%2C%22time%22%3A15672%2C%22variable%22%3A%22magwatervel%22%2C%22variable_scale%22%3A%5B0%2C1%5D%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A15672%2C%22output_format%22%3A%22NETCDF4%22%2C%22output_starttime%22%3A15672%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22magwatervel%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%220%2C1%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22setDefaultScale%22%3Atrue%2C%22showarea%22%3Afalse%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22syncLocalToGlobalState%22%3Afalse%2C%22zip%22%3Afalse%7D%2C%22time%22%3A15672%2C%22variable%22%3A%22magwatervel%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A4%7D

**Comment by htmlboss** [comment]
Stack trace:
```sh
[2020-04-09 16:22:45 +0000] [4339] [ERROR] Error handling request /api/v1.0/plot/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B49.95121990866204%2C-42.93457031249999%5D%2C%5B50.56928286558244%2C-52.1630859375%5D%2C%5B44.59046718130884%2C-53.745117187499986%5D%2C%5B43.96119063892027%2C-42.758789062499986%5D%2C%5B49.95121990866204%2C-42.93457031249999%5D%5D%5D%7D%5D%2C%22bathymetry%22%3Atrue%2C%22colormap%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22interp%22%3A%22gaussian%22%2C%22neighbours%22%3A10%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22quantum%22%3A%22day%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22magwatervel%22%7D%2C%22radius%22%3A25%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22showarea%22%3Atrue%2C%22time%22%3A2217585600%2C%22type%22%3A%22map%22%2C%22variable%22%3A%22votemper%22%7D&format=json
Traceback (most recent call last):
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/buildadm/Ocean-Data-Map-Project/routes/api_v1_0.py", line 554, in plot_v1_0
    img, mime, filename = plotter.run()
  File "/home/buildadm/Ocean-Data-Map-Project/plotting/plotter.py", line 58, in run
    _ = self.prepare_plot()
  File "/home/buildadm/Ocean-Data-Map-Project/plotting/plotter.py", line 51, in prepare_plot
    self.load_data()
  File "/home/buildadm/Ocean-Data-Map-Project/plotting/map.py", line 291, in load_data
    self.neighbours,
  File "/home/buildadm/Ocean-Data-Map-Project/data/model.py", line 122, in get_area
    latitude, longitude, depth, variable, time, return_depth=return_depth
  File "/home/buildadm/Ocean-Data-Map-Project/data/mercator.py", line 263, in get_point
    data = var[time_slice, int(depth), miny:maxy, minx:maxx]
  File "/home/buildadm/Ocean-Data-Map-Project/data/calculated.py", line 128, in __getitem__
    self._expression, self._parent, key, self._dims)
  File "/home/buildadm/Ocean-Data-Map-Project/data/calculated_parser/parser.py", line 48, in parse
    self.parser.parse(expression)
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/ply/yacc.py", line 1120, in parseopt_notrack
    p.callable(pslice)
  File "/home/buildadm/Ocean-Data-Map-Project/data/calculated_parser/parser.py", line 101, in p_expression_variable
    t[0] = self.data.variables[t[1]][
  File "/home/buildadm/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/utils.py", line 317, in __getitem__
    return self.mapping[key]
KeyError: 'vozocrtx'
```
```
