### ISSUE TITLE
Issue with uploading new observational  datasets to MariaDB

### ISSUE THREAD

**Issue by dwayne-hart** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#790]
On hank, I have setup two Docker containers. The first one is a MariaDB instance which allows me to try out the various Python scripts that Geoff had included in his work. The second Docker instance has a current version of the Ocean Navigator installed and is able to communicate to the MariaDB instance over port 3306. The aforementioned scripts reside in the […]/Ocean-Data-Map-Project/scripts/data_importers directory. The 

I was able to get the argo.py script to work and have 3120 platform entries. However, when I went to use the glider.py and the seal.py scripts I ran into issues.

I copied the aforementioned scripts into the root of the […]/Ocean-Data-Map-Project directory so that it could use a couple of the Ocean Navigator libraries.

```
(navigator) ubuntu@580dc126ebb8:~/Ocean-Data-Map-Project$ ./glider.py --help
usage: glider.py [-h] uri filename

Import Glider NetCDF

positional arguments:
  uri         Database URI
  filename    Glider Filename, or directory of NetCDF files

optional arguments:
  -h, --help  show this help message and exit

```
When I try to read in /data/glider/SEA022_20190806_R.nc or /data/glider/SEA022_20190806_R/R4800993_20190806_081.nc 
```
(navigator) ubuntu@580dc126ebb8:~/Ocean-Data-Map-Project$ ./glider.py mysql://onav:PdF2an1pYfL0@172.17.0.3/navigator          
/data/glider/SEA022_20190806_R.nc
Traceback (most recent call last):
  File "./glider.py", line 101, in <module>
    defopt.run(main)
  File "/home/ubuntu/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/defopt.py", line 167, in run
    return _call_function(parser, args._func, args)
  File "/home/ubuntu/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/defopt.py", line 511, in _call_function
    return func(*positionals, **keywords)
  File "./glider.py", line 54, in main
    unique_id=f"glider_{ds.deployment_label}")
  File "/home/ubuntu/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/common.py", line 179, in __getattr__
    (type(self).__name__, name))
AttributeError: 'Dataset' object has no attribute 'deployment_label'
```
The closest that I could find to a ‘deployment_label’ is the following…
```
        char DEPLOYMENT_PLATFORM(STRING32) ;
                DEPLOYMENT_PLATFORM:long_name = "Identifier of the deployment platform" ;
                DEPLOYMENT_PLATFORM:_FillValue = " " ;
        char DEPLOYMENT_CRUISE_ID(STRING32) ;
                DEPLOYMENT_CRUISE_ID:long_name = "Identifier of the cruise that deployed the glider" ;
                DEPLOYMENT_CRUISE_ID:_FillValue = " " ;
        char DEPLOYMENT_REFERENCE_STATION_ID(STRING256) ;
                DEPLOYMENT_REFERENCE_STATION_ID:long_name = "Identifier of stations used to verify the parameter measurements" ;
                DEPLOYMENT_REFERENCE_STATION_ID:_FillValue = " " ;

(navigator) ubuntu@580dc126ebb8:~/Ocean-Data-Map-Project$ ./glider.py mysql://onav:PdF2an1pYfL0@172.17.0.3/navigator /data/glider/SEA022_20190806_R/R4800993_20190806_081.nc
/data/glider/SEA022_20190806_R/R4800993_20190806_081.nc
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/dataset.py", line 879, in _copy_listed
    variables[name] = self._variables[name]
KeyError: 'TIME'
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "./glider.py", line 101, in <module>
    defopt.run(main)
  File "/home/ubuntu/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/defopt.py", line 167, in run
    return _call_function(parser, args._func, args)
  File "/home/ubuntu/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/defopt.py", line 511, in _call_function
    return func(*positionals, **keywords)
  File "./glider.py", line 33, in main
   ['TIME', 'LATITUDE', 'LONGITUDE', 'PRES', *variables]
  File "/home/ubuntu/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/dataset.py", line 972, in __getitem__
    return self._copy_listed(np.asarray(key))
  File "/home/ubuntu/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/dataset.py", line 882, in _copy_listed
    self._variables, name, self._level_coords, self.dims)
  File "/home/ubuntu/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/xarray/core/dataset.py", line 74, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'TIME'
```

When I look at the header information for /data/glider/SEA022_20190806_R/R4800993_20190806_081.nc there is no TIME key. 
```
(navigator) ubuntu@580dc126ebb8:~/Ocean-Data-Map-Project$ cat /tmp/SEA022_20190806_R-R4800993_20190806_081_header.info | grep TIME
        DATE_TIME = 14 ;
        char REFERENCE_DATE_TIME(DATE_TIME) ;
                REFERENCE_DATE_TIME:long_name = "Date of reference for Julian days" ;
                REFERENCE_DATE_TIME:conventions = "YYYYMMDDHHMISS" ;
                REFERENCE_DATE_TIME:_FillValue = " " ;
        char DATE_CREATION(DATE_TIME) ;
        char DATE_UPDATE(DATE_TIME) ;
                JULD:long_name = "Julian day (UTC) of the station relative to REFERENCE_DATE_TIME" ;
                JULD_LOCATION:long_name = "Julian day (UTC) of the location relative to REFERENCE_DATE_TIME" ;
        char SCIENTIFIC_CALIB_DATE(N_PROF, N_CALIB, N_PARAM, DATE_TIME) ;
        char HISTORY_DATE(N_HISTORY, N_PROF, DATE_TIME) ;
```
Thoughts, musings, and suggestions welcome.

**Comment by jmunroe** [comment]
I'd assume the scripts were designed to import a slightly different format of glider data.  Is all of the glider data we need to import in the following files?

/data/glider/*_R.nc or /data/glider/*_R/*.nc

Assuming there are no other files we can update the glider.py script as need. If there is additional set of glider data that needs to be imported, please advise.

In either case, we need to make the data files in /data/glider world-readable so I can proceed:

```dr-x------ 2 nobody nogroup  194 Apr  4  2019 SEA019_20190314_R
-r-x------ 1 nobody nogroup 6.8M Apr 15  2019 SEA019_20190314_R.nc
dr-x------ 2 nobody nogroup   96 Nov 12  2019 SEA019_20191022_R
-r-x------ 1 nobody nogroup 7.2M Nov 13  2019 SEA019_20191022_R.nc
dr-x------ 2 nobody nogroup  113 Mar  8  2020 SEA019_20200217_R
-r-x------ 1 nobody nogroup 5.4M Mar 10  2020 SEA019_20200217_R.nc```

**Comment by dwayne-hart** [comment]
I'm not sure why the directory and file permissions are so restrictive as the account has a somewhat liberal unmask. I'll gladly fix that within the hour.

**Comment by dwayne-hart** [comment]
The directories has been changed to 755 and the files are 644 for the glider directory and its content.

**Comment by jmunroe** [comment]
"DEPLOYMENT_PLATFORM" looks generally blank to me.  I think for the glider data in the files with filenames

`/data/glider/*_R.nc`

it would be appropriate to replace the line in the glider.py refering to `ds.deployment_label` to `ds.id` instead.

Also,  we probably should remove the lines 58 and 60:
```
 'Contact': ds.contact,
 'Deployment': ds.deployment_label,
```

since those fields are not in these types of datasets.

The files with names of the form

`/data/glider/*_R/*/nc`

are a bit harder to interpret.  Is that Argo profile data? Or is that glider data that has been converted to the Argo vertical profile format for some purpose?   The 'time' information is in the JULD field (as in Julian Day since some reference).  Importing these files would be done with the `argo.py` script (if that is even needed)
