### ISSUE TITLE
Transect in Arctic projection fails when requesting map location.

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#83]
Something is throwing an exception within the `m.etoop()` call on line 133 of utils.py.

When the "Show Map Location" box is checked, Python spits out the following error:

```
Traceback (most recent call last):
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nabil/ocean-navigator/oceannavigator/views.py", line 569, in plot
    img, mime, filename = plotter.run(size=size, dpi=request.args.get('dpi'))
  File "/home/nabil/ocean-navigator/plotting/plotter.py", line 55, in run
    return self.plot()
  File "/home/nabil/ocean-navigator/plotting/transect.py", line 429, in plot
    utils.path_plot(self.transect_data['points'])
  File "/home/nabil/ocean-navigator/plotting/utils.py", line 160, in path_plot
    _map_plot(points, True, quiver=quiver)
  File "/home/nabil/ocean-navigator/plotting/utils.py", line 133, in _map_plot
    m.etopo()
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 4049, in etopo
    return self.warpimage(image='etopo',scale=scale,**kwargs)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 4174, in warpimage
    self._bm_rgba_warped = np.ones((ny,nx,4),np.float64)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/numpy/core/numeric.py", line 190, in ones
    a = empty(shape, dtype, order)
ValueError: Maximum allowed dimension exceeded
```

When surrounded with a try/except block:

```
Traceback (most recent call last):
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nabil/ocean-navigator/oceannavigator/views.py", line 569, in plot
    img, mime, filename = plotter.run(size=size, dpi=request.args.get('dpi'))
  File "/home/nabil/ocean-navigator/plotting/plotter.py", line 55, in run
    return self.plot()
  File "/home/nabil/ocean-navigator/plotting/transect.py", line 692, in plot
    return super(TransectPlotter, self).plot(fig)
  File "/home/nabil/ocean-navigator/plotting/plotter.py", line 176, in plot
    pad_inches=0.5,
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 688, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1565, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2180, in print_figure
    **kwargs)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 474, in draw
    self.figure.draw(self.renderer)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1159, in draw
    func(*args)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2324, in draw
    a.draw(renderer)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/quiver.py", line 526, in draw
    self._init()
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/quiver.py", line 502, in _init
    sx, sy = trans.inverted().transform_point(
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/matplotlib/transforms.py", line 1775, in inverted
    self._inverted = Affine2D(inv(mtx), shorthand_name=shorthand_name)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 526, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/opt/tools/anaconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
LinAlgError: Singular matrix
```

If the box is unchecked, the plot renders correctly.

**Comment by Jeffreydaw** [comment]
This problem only exists for plots at are made above 85deg lat.

[working example 1](http://navigator.oceansdata.ca/public/?query=%7B%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%227.7328%22%2C%2279.2209%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22depth%22%3A0%2C%22starttime%22%3A-2%2C%22time%22%3A789%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A0%2C%22line%22%3A%5B%5B%5B82.04489853967966%2C-13.655093987909979%5D%2C%5B82.04093864563512%2C-9.878355646667133%5D%5D%5D%2C%22modal%22%3A%22line%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A32661%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22colormap%22%3A%22default%22%2C%22colormap_diff%22%3A%22default%22%2C%22colormap_right%22%3A%22default%22%2C%22depth_limit%22%3Afalse%2C%22dpi%22%3A144%2C%22linearthresh%22%3A200%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22selected%22%3A1%2C%22showmap%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%7D%2C%22time%22%3A789%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A4%7D)

**Comment by htmlboss** [comment]
Basemap trash needs to be replaced eventually.
