### ISSUE TITLE
change in kml path causing test_query_endpoint to fail

### ISSUE THREAD

**Issue by jmunroe** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#890]
```
======================================================================
ERROR: test_query_endpoint (tests.test_api_v_1_0.TestAPIv1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmunroe/Ocean-Data-Map-Project/tests/test_api_v_1_0.py", line 386, in test_query_endpoint
    '/api/v1.0/points/'
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/werkzeug/test.py", line 830, in get
    return self.open(*args, **kw)
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/testing.py", line 127, in open
    follow_redirects=follow_redirects)
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/werkzeug/test.py", line 803, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/werkzeug/test.py", line 716, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/sentry_sdk/integrations/flask.py", line 90, in sentry_patched_wsgi_app
    environ, start_response
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/sentry_sdk/integrations/wsgi.py", line 131, in __call__
    reraise(*_capture_exception(hub))
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/sentry_sdk/integrations/wsgi.py", line 127, in __call__
    _sentry_start_response, start_response, transaction
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/sentry_sdk/integrations/flask.py", line 89, in <lambda>
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jmunroe/miniforge3/envs/navigator-env/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jmunroe/Ocean-Data-Map-Project/routes/api_v1_0.py", line 680, in query_v1_0
    data = utils.misc.list_kml_files('point')
  File "/home/jmunroe/Ocean-Data-Map-Project/utils/misc.py", line 23, in list_kml_files
    for f in os.listdir(DIR):
FileNotFoundError: [Errno 2] No such file or directory: './kml/point'

----------------------------------------------------------------------
Ran 1 test in 0.010s

FAILED (errors=1)
```

**Comment by jmunroe** [comment]
My mistake. Need to update the submodule `oceannavigator/configs` as well.
