### ISSUE TITLE
Issue plotting argo observation tracks 

### ISSUE THREAD

**Issue by dwayne-hart** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#927]
Environment: new navigator toolchain
Code branch: Performance-Testing

When an area is selected in the North Atlantic requesting all available Argo data for monthly average in the time range of 2020-01-01 and 2021-12-08. The following error is encountered;

```
[2021-12-08 17:46:23 -0330] [6219] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 343, in handle_request
    util.reraise(*sys.exc_info())
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/gunicorn/util.py", line 626, in reraise
    raise value
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/sentry_sdk/integrations/flask.py", line 90, in sentry_patched_wsgi_app
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 140, in __call__
    reraise(*_capture_exception(hub))
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 133, in __call__
    rv = self.app(
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/sentry_sdk/integrations/flask.py", line 90, in <lambda>
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/site-packages/werkzeug/middleware/profiler.py", line 128, in __call__
    profile.dump_stats(filename)
  File "/home/on/tools/miniconda/3/amd64/envs/navigator-2021.12/lib/python3.8/cProfile.py", line 46, in dump_stats
    with open(file, 'wb') as f:
OSError: [Errno 36] File name too long: './profiler_results/GET.api.v1.0.observation.track.start_date=2020-01-01;end_date=2021-12-09;area=[[59.98669914224615,-51.660308837890646],[31.819358694792385,-66.95327758789064],[31.744646559867988,-11.406402587890641],[61.363901134352574,-9.121246337890637],[59.98669914224615,-51.660308837890646]];quantum=month;platform_type=argo;meta_key=Any;meta_value=.json.1876ms.1638998184.prof'
```
The environment.yml file was updated to include both mysql-connector-python and mysqlclient modules. In order for flask-sqlalchemy to be able to interact with the MariaDB instance within our lab.

The environment.yml file now has the following information;

```
name: navigator-2021.12
channels:
  - conda-forge
dependencies:
  - python=3.8
  - flask
  - basemap
  - basemap-data-hires
  - blinker
  - cachetools
  - cloudpickle
  - cmocean
  - dask
  - flask-babel
  - flask-compress
  - flask-sqlalchemy
  - gdal
  - geopy
  - gunicorn
  - geojson
  - marshmallow
  - matplotlib
  - metpy
  - mysql-connector-python
  - mysqlclient
  - netcdf4
  - numpy
  - pandas
  - pip
  - ply
  - pykdtree
  - pyresample
  - requests
  - scikit-image
  - scipy
  - seawater
  - sentry-sdk
  - xarray
  - sqlalchemy
  - werkzeug
  - zarr
  - pip:
    - visvalingamwyatt
```

**Comment by dwayne-hart** [comment]
This was resolved by commenting out the profiler lines.
